### ISSUE TITLE
I've heard you like iframes....

### ISSUE THREAD

**Issue by etiennesegonzac** [etiennesegonzac/APZ-gambler#1]
So... here's the plan.

Currently each `tab` is a bunch of markup with a screenshot inside.
What we want (for flexibility, performance, and easy experimentation) is to adopt the following architecture.

Each `tab` is a (classic) iframe containing:
- the `header` DOM
- the chrome DOM (url bar, reload button and all)
- the chrome css style
- the tab header css style
- the mozbrowser iframe containing the page (iframes!)

The hope tab manager will create and manager those tabs iframe, each tab will need to expose the following bridge API:
- expanding/collapsing the chrome
- setting the url
- going back/forward

**Comment by wilsonpage** [comment]
What the main reason each tab should be an `<iframe>`?

**Comment by etiennesegonzac** [comment]
The main reason if flexibility / decoupling.
We're setting up a test bed for UX experiments and we'll probably have separate experiment running in parallel.

It will be really useful to be able to hack at full speed on tab management and the navigation/chrome at the same time :)

**Comment by wilsonpage** [comment]
Custom Elements might be a lighter way to achieve the same goals? We could have a `<hope-tab>` that contains the `mozbrowser` iframe...?

**Comment by etiennesegonzac** [comment]
That's true.
Then there's the whole memory management part of the debate...

I'm going to play my "who codes decides" card :)

The priority is to have real web content in the prototype ASAP, close second having it decoupled enough to enable further experiments. But I'm fine with either iframes or `hope-tab`s :)
