### ISSUE TITLE
Check if we can remove the make step for the addon

### ISSUE THREAD

**Issue by etiennesegonzac** [etiennesegonzac/APZ-gambler#13]
@arcturus you might be able to help :)

**Comment by jonathanKingston** [comment]
Was not able to get it built onto b2gdroid with or without... however it could just be my setup the WebIDE requires 10 starts to install on my phone without it timing out.

**Comment by wilsonpage** [comment]
Do we even need the `manifest.webapp` anymore? Or do we still want to support this being able to replace the system app?

**Comment by wilsonpage** [comment]
I don't seem to require the Make step to flash an updated version of the add-on using WebIDE.

**Comment by wilsonpage** [comment]
Suggestions:
- Remove `manifest.webapp` as it's not required right now and conflicts with `manifest.json`
- Remove 'addon' Makefile task
- Move scripts to `package.json` and remove `Makefile`

**Comment by etiennesegonzac** [comment]
Some of this will break the b2gdroid build!

**Comment by wilsonpage** [comment]
> Some of this will break the b2gdroid build!

Ah, I'm not aware of how the b2gdroid build works. Can it not use the addon?

**Comment by etiennesegonzac** [comment]
> Ah, I'm not aware of how the b2gdroid build works. Can it not use the addon?

Well the goal is to use the native keyboard/notification tray. Seems super overkill to load all gaia into the apk and all the system app onto the phone just to show an iframe with an addon. And we'd still need a special build step to build the addon in/enable it by default.

So I really want to keep the b2gdroid support in. We need the manifest.webapp, the shallow profile dir and the profile Makefile task.
Doesn't mean we can't clean it up :)

**Comment by wilsonpage** [comment]
Makes sense. Soz, I didn't know anything about the b2g-droid requirements.

**Comment by etiennesegonzac** [comment]
That's my bad. I'll write up an actually useful Readme.md, it should help :)

**Comment by etiennesegonzac** [comment]
I'm rewriting the Readme.md and taking a look at this issue at the same time.

**Comment by etiennesegonzac** [comment]
Fixed by #23
