### ISSUE TITLE
`http://` should be automatically prepended when the URL is laking one

### ISSUE THREAD

**Issue by etiennesegonzac** [etiennesegonzac/APZ-gambler#33]

**Comment by jonathanKingston** [comment]
Can it try https first please?

**Comment by etiennesegonzac** [comment]
Of course, but the patch will probably be a bit bigger and we'll need to listen the mozbrowsererror to adjust.

**Comment by jonathanKingston** [comment]
I'm happy to take a look at that side if no one is interested?

**Comment by etiennesegonzac** [comment]
All clear, feel free to take a crack at this one :)

**Comment by jonathanKingston** [comment]
@etiennesegonzac thanks do you know if there is a plan for a settings page at all? (Personally I would like to turn the fallback off or at least prompt etc)

**Comment by etiennesegonzac** [comment]
We don't have that detailed of the plan right now :)
The goal is really just to enable basic browsing first then go from there.

**Comment by jonathanKingston** [comment]
I may have accidentally implemented search whilst doing this bug :stuck_out_tongue: 

So currently it operates on urls that don't validate with the `new URL(url)` object:
- if the URL has something that looks like a protocol then it will fail (I can't think of better behaviour here)
- if the URL looks like it has a domain extension then it won't try to search
- it will search currently with ddg
- if there isn't a valid protocol then it will try adding 'https://'

However I'm slightly reluctant to just throw in the downgrade as all this happens on users typing in the URL for the time being. However the error event would fire for any failing URLs which would mean any failure in HTTPS would downgrade to HTTP which would be super bad in places where a nation state actor is an issue etc.

I can show you where I am so far for comments etc whilst I think through how to implement the downgrading safely.

**Comment by jonathanKingston** [comment]
@etiennesegonzac initial work here: https://github.com/jonathanKingston/hope/commit/230f6fc2a4ea9ee21b0bc80ce9be405f750b1991 going for dinner :smile: needs tests etc and lots of love.

**Comment by jonathanKingston** [comment]
@etiennesegonzac Long term I think something similar to the History API will be needed to be synthesized on top of each tab to provide robust url changes on when a user typed an address vs navigation.
I didn't get chance to write tests but it mostly seems to be working: https://github.com/jonathanKingston/hope/commit/e84c8dad9fc1ba38bd7e7049f44d15ba378e788d

**Comment by etiennesegonzac** [comment]
@jonathanKingston looks really promising, and already a net win for our short term goal of "making basic browsing usable". Send the PR :)
