### ISSUE TITLE
Opening and closing tabs

### ISSUE THREAD

**Issue by jonathanKingston** [etiennesegonzac/APZ-gambler#50]
I keep seeing the following error in the webIDE: 'TypeError: hopeFrame.contentWindow is null' addon.js:98:5

I'm on an fxp build for a Z3 leo.

For each key press of the home button I seem to get 4 or so of the same error.

**Comment by etiennesegonzac** [comment]
Mmmh... looks like the addon is not getting the system app privileges on your build.
It's strange but it might explain the issues you're having with #49

**Comment by etiennesegonzac** [comment]
This probably only happens when the addon has been flashed multiple time on device (without a reboot).
We remove the dom/css but the JS from the previous flash is still running and has a reference to a now staled iframe.

**Comment by jonathanKingston** [comment]
@etiennesegonzac I was thinking it was that, just didn't have time to debug. I'll see if I can clean up the handlers when the addon is removed.
